config/routes.rb
Rails.application.routes.draw do
  # 顧客のルーティング↓
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # ゲストログインのルーティング
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    get "/about" => "homes#about", as: "about"
    get '/privacy' => "homes#privacy", as: "privacy"
    get '/terms_of_service' => "homes#terms_of_service", as: "terms_of_service"
    get "/my_page", to: "users#my_page", as: "my_page"
    get '/users/:id', to: 'users#show', as: 'user'
    resources :users, except: [:new, :show,:destroy] do
      member do
        get :likes
      end
      resource :relationship, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    # 退会確認用のルーティング
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :chats, only: [:show, :create, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :genres, only: [:index,:show]
    resources :inquiries, only: [:new, :create, :index, :show]
  end

  #ここから管理者のルーティング↓
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '' => "homes#top"
    resources :genres, except: [:new]
    resources :posts, only: [:show, :destroy]
    resources :users, except: [:new, :destroy]
    resources :comments, only: [:destroy]
    resources :inquiries, only: [:index, :show] do
      member do
        patch 'respond'
        get "send_mail"
      end
    end
    get "search" => "searches#search"
  end

  get '/favicon.ico', to: proc { [204, {}, []] }
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user
# エンドユーザーのバリデーション
  validates :title, :message, presence: true
# 管理者のみ適用のバリデーション
  with_options if: :admin_context? do
    validates :response, presence: true
  end

  # スコープ
  scope :answered, -> { where(answered: true).order(created_at: :desc) }
  scope :unanswered, -> { where(answered: false).order(created_at: :desc) }

  private
# バリデーションのコンテキストがadminの
  def admin_context?
    validation_context == :admin
  end
end

app/controllers/admin/inquiries_controller.rb
class Admin::InquiriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_inquiry, only: [:show, :respond, :send_mail]
  before_action :set_sidebar

  def index
    @sort_option = if params[:answered]
                      'answered'
                   elsif params[:unanswered]
                      'unanswered'
                   else
                      'default'
                   end

    @inquiries = case @sort_option
                 when 'answered'
                   Inquiry.answered.page(params[:page])
                 when 'unanswered'
                   Inquiry.unanswered.page(params[:page])
                 else
                   Inquiry.all.order(created_at: :desc).page(params[:page])
                 end
  end

  def show
  end

  def respond
    # assign_attributes: オブジェクトの属性を一括して設定するが、データベースへの保存は行わない。
    @inquiry.assign_attributes(response_params.merge(answered: 'answered'))

    # context: :admin: バリデーションのコンテキストを指定し、特定の条件下でのみバリデーションを実行する
    if @inquiry.save(context: :admin)
      ContactMailer.response_email(@inquiry).deliver_now
      redirect_to send_mail_admin_inquiry_path, notice: 'ステータス変更と返信が完了しました。'
    else
      flash[:alert] = "送信に失敗しました。"
      flash[:inquiry_errors] = @inquiry.errors.full_messages
      redirect_to admin_inquiry_path(@inquiry)
    end
  end

  def send_mail
  end


  private

  def response_params
    params.require(:inquiry).permit(:response)
  end

  def set_inquiry
    @inquiry = Inquiry.find(params[:id])
  end

  def set_sidebar
    @show_sidebar = false
  end

end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/views/admin/inquiries/index.html.erb
<h4 class="text-center">問い合わせ一覧</h4>

<ul class="nav nav-underline justify-content-center mb-3">
  <li class="nav-item">
    <%= link_to "回答済", admin_inquiries_path(answered: "true"), class: "nav-link #{'active' if @sort_option == 'answered'}" %>
  </li>
  <li class="nav-item">
    <%= link_to "未回答", admin_inquiries_path(unanswered: "true"), class: "nav-link #{'active' if @sort_option == 'unanswered'}" %>
  </li>
</ul>

<div class="row justify-content-center text-center">
  <div class="col-11 col-md-10 col-lg-6 my-5">
    <% if @inquiries.exists? %>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>問い合わせ内容</th>
              <th>ユーザー名</th>
              <th>問い合わせステータス</th>
              <th>詳細</th>
            </tr>
          </thead>
          <tbody>
            <% @inquiries.each do |inquiry| %>
              <tr>
                <td><%= inquiry.title %></td>
                <td>
                  <%= link_to admin_user_path(inquiry.user) do %>
                    <%= inquiry.user.name %>
                  <% end %>
                </td>
                <td>
                  <% if inquiry.answered? %>
                    <span class="text-success"><strong>回答済</strong></span>
                  <% else %>
                    <span class="text-muted"><strong>未回答</strong></span>
                  <% end %>
                </td>
                <td><%= link_to "詳細", admin_inquiry_path(inquiry), style: "color: #3e8d92;"%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <% else %>
      <p>問い合わせはありません。</p>
    <% end %>
  </div>
</div>
<div class="row justify-content-center mb-5">
  <div class="col-6">
    <%= paginate @inquiries %>
  </div>
</div>

app/views/admin/inquiries/send_mail.html.erb
<div class="row justify-content-center my-5">
  <div>
    <h2 class="mb-3">送信が完了しました</h2>
    <p>内容は以下の通りです。</p>
    <div>
      [タイトル]<p class="font-weight-bold"><%= @inquiry.title %></p>
    </div>
    <div>
      [本文]<p class="font-weight-bold"><%= safe_join(@inquiry.response.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-11 col-md-10 col-lg-6 text-right">
    <%= link_to "問い合わせ一覧に戻る", admin_inquiries_path, class: "btn btn_return" %>
  </div>
</div>

app/views/admin/inquiries/show.html.erb
<h4 class="text-center">問い合わせ詳細</h4>
<div class="row justify-content-center">
  <div class="card col-11 col-md-10 col-lg-6 my-5">
    <div class="row my-3">
      <span class="col-6">問い合わせの内容</span>
      <span class="col-6"><%= @inquiry.title %></span>
    </div>
    <div class="row mb-3">
      <span class="col-6">ユーザー名</span>
      <span class="col-6"><%= @inquiry.user.name %></span>
    </div>
    <div class="row mb-3">
      <span class="col-6">問い合わせの詳細</span>
      <span class="col-6"><%= @inquiry.message %></span>
    </div>
    <div class="row mb-5">
      <span class="col-6">問い合わせ状況</span>
      <span class="col-6">
        <% if @inquiry.answered? %>
          <span class="text-success"><strong>回答済</strong></span>
        <% else %>
          <span class="text-muted"><strong>未回答</strong></span>
        <% end %>
      </span>
    </div>
    <% if flash[:inquiry_errors].present? %>
      <div class="mt-4">
        <div class="alert alert-danger">
          <ul>
            <% flash[:inquiry_errors].each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <%= form_with model: @inquiry, url: respond_admin_inquiry_path(@inquiry), method: :patch do |f| %>
      <div class="form-group row">
        <%= f.label "返信",class: "col-3" %>
        <%= f.text_area :response, row: 5 ,class: "col-8 form-control" %>
      </div>
      <div class="form-group row">
        <div class="col-11 text-right">
          <%= f.submit "送信", class: "btn btn_post" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row justify-content-center mb-5">
  <div class="col-11 col-md-10 col-lg-6 text-right">
    <%= link_to "問い合わせ一覧に戻る", admin_inquiries_path, class: "btn btn_return" %>
  </div>
</div>