config/routes.rb
Rails.application.routes.draw do
  # 顧客のルーティング↓
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # ゲストログインのルーティング
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    get "/about" => "homes#about", as: "about"
    get '/privacy' => "homes#privacy", as: "privacy"
    get '/terms_of_service' => "homes#terms_of_service", as: "terms_of_service"
    get "/my_page", to: "users#my_page", as: "my_page"
    get '/users/:id', to: 'users#show', as: 'user'
    resources :users, except: [:new, :show,:destroy] do
      member do
        get :likes
      end
      resource :relationship, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    # 退会確認用のルーティング
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :chats, only: [:show, :create, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :genres, only: [:index,:show]
    resources :inquiries, only: [:new, :create, :index, :show]
  end

  #ここから管理者のルーティング↓
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '' => "homes#top"
    resources :genres, except: [:new]
    resources :posts, only: [:show, :destroy]
    resources :users, except: [:new, :destroy]
    resources :comments, only: [:destroy]
    resources :inquiries, only: [:index, :show] do
      member do
        patch 'respond'
        get "send_mail"
      end
    end
    get "search" => "searches#search"
  end

  get '/favicon.ico', to: proc { [204, {}, []] }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_one :notification, as: :subject, dependent: :destroy

  validates :comment, presence: true

  include NotificationConcern

  after_create :create_notifications

  def create_notifications
    create_notification(self.post.user, self, :commented_to_own_post)
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_comment, only: [:destroy]

  def destroy
    @comment.destroy
    redirect_to request.referer, notice: 'コメントを削除しました。'
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_index.html.erb
<table class="table col-12 col-lg-auto">
  <thead>
    <tr>
      <th class="comment_list">コメント一覧</th>
      <th> <span id="comment_counter">コメント数 <%= @post.comments.count %></span></th>
      <th class="text-center">コメントの感情分析</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% if post.comments.exists? %>
      <% post.comments.each do |comment| %>
        <tr>
          <td>
            <%= link_to admin_user_path do %>
              <%= image_tag comment.user.get_profile_image, size: "40x40", style: 'border-radius: 50%', class: "border border-dark-subtle" %>
              <span class="mx-2"><%= comment.user.name %></span>
            <% end %>
          </td>
          <td><%= comment.comment %></td>

          <!--コメントの感情分析の点数-->
          <td class="sentiment-score text-center">[<%= comment.score %>]</td>

          <td>
            <%= link_to admin_comment_path(comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn_delete" do %>
              削除 <i class="fa-solid fa-trash-can"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td><p>コメントはありません。</p></td>
      </tr>
    <% end %>
  </tbody>
</table>