config/routes.rb
Rails.application.routes.draw do
  # 顧客のルーティング↓
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # ゲストログインのルーティング
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    get "/about" => "homes#about", as: "about"
    get '/privacy' => "homes#privacy", as: "privacy"
    get '/terms_of_service' => "homes#terms_of_service", as: "terms_of_service"
    get "/my_page", to: "users#my_page", as: "my_page"
    get '/users/:id', to: 'users#show', as: 'user'
    resources :users, except: [:new, :show,:destroy] do
      member do
        get :likes
      end
      resource :relationship, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    # 退会確認用のルーティング
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :chats, only: [:show, :create, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :genres, only: [:index,:show]
    resources :inquiries, only: [:new, :create, :index, :show]
  end

  #ここから管理者のルーティング↓
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '' => "homes#top"
    resources :genres, except: [:new]
    resources :posts, only: [:show, :destroy]
    resources :users, except: [:new, :destroy]
    resources :comments, only: [:destroy]
    resources :inquiries, only: [:index, :show] do
      member do
        patch 'respond'
        get "send_mail"
      end
    end
    get "search" => "searches#search"
  end

  get '/favicon.ico', to: proc { [204, {}, []] }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    if params[:latest]
      @posts = Post.latest.page(params[:page])
    elsif params[:old]
      @posts = Post.old.page(params[:page])
    elsif params[:most_favorites]
      @posts = Post.most_favorites.page(params[:page])
    else
      @posts = Post.all.order(created_at: :desc).page(params[:page])
    end
    # サイドバー適応のため
    @genres = Genre.all.page(params[:sidebar_page]).per(5)
    @total_genres_count = Genre.count
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/_index.html.erb
<% posts.each do |post| %>
  <% if post.user.is_active? %>
    <div class="card shadow m-2" style="width: 18rem;">
      <%= link_to admin_post_path(post) do %>
        <div class="card-img-top border-bottom">
          <%= image_tag post.get_complete_image, size: "200x250", class: "card-img-top"  %>
        </div>
        <div class="card-body">
          <h5 class="card-title text-center"><%= post.title.truncate(9) %></h5>
        </div>
      <% end %>
      <!--ユーザー情報-->
      <div class="card-text p-2">
        <%= link_to admin_user_path(post.user), class: "name_link" do %>
          <%= image_tag post.user.get_profile_image, size: "40x40", style: 'border-radius: 50%', class: "border border-dark-subtle" %>
          <%= post.user.name %>
        <% end %>
      </div>
      <!--いいね＆コメント数-->
      <div class="card-link d-flex justify-content-end border-top pt-3 px-3">
        <div class="mr-2"><i class="fa-regular fa-comment"></i><%= post.comments.count %></div>
        <div style="color: red;">
          <i class="fa-solid fa-heart"></i>
          <%= post.favorites.count %>
        </div>
      </div>
      <div class="pb-2 px-2">
        <%= l post.created_at %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/homes/top.html.erb
<h4 class="text-center">投稿一覧</h4>
<p class="text-center my-3">
  <%= link_to "新しい順", admin_path(latest: "true"), style: "color: #027b71;" %>
  / <%= link_to "古い順", admin_path(old: "true"), style: "color: #027b71;" %>
  / <%= link_to "評価の高い順", admin_path(most_favorites: "true"), style: "color: #027b71;" %>
</p>
<div class="row justify-content-center d-flex flex-wrap mb-5">
  <% if @posts.exists? %>
    <%= render 'index', posts: @posts %>
  <% else %>
    <h6>投稿はされていません</h6>
  <% end %>
</div>
<div class="row justify-content-center mb-5">
  <div class="col-6">
    <%= paginate @posts %>
  </div>
</div>