config/routes.rb
Rails.application.routes.draw do
  # 顧客のルーティング↓
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # ゲストログインのルーティング
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    get "/about" => "homes#about", as: "about"
    get '/privacy' => "homes#privacy", as: "privacy"
    get '/terms_of_service' => "homes#terms_of_service", as: "terms_of_service"
    get "/my_page", to: "users#my_page", as: "my_page"
    get '/users/:id', to: 'users#show', as: 'user'
    resources :users, except: [:new, :show,:destroy] do
      member do
        get :likes
      end
      resource :relationship, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    # 退会確認用のルーティング
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :chats, only: [:show, :create, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :genres, only: [:index,:show]
    resources :inquiries, only: [:new, :create, :index, :show]
  end

  #ここから管理者のルーティング↓
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '' => "homes#top"
    resources :genres, except: [:new]
    resources :posts, only: [:show, :destroy]
    resources :users, except: [:new, :destroy]
    resources :comments, only: [:destroy]
    resources :inquiries, only: [:index, :show] do
      member do
        patch 'respond'
        get "send_mail"
      end
    end
    get "search" => "searches#search"
  end

  get '/favicon.ico', to: proc { [204, {}, []] }
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li style="color: red;"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<div class="p-3 text-center"style="background-color: #e9c9d5;">
  <span class="footer_link mx-3" style= "color: #3e8d92;">©Oshi Life.Inc</span>
  <% unless admin_signed_in? %>
    <%= link_to "Oshi Lifeについて", about_path, class: "footer_link mx-3", style: "color: #3e8d92;" %>
    <%= link_to "利用規約", terms_of_service_path, class: "footer_link mx-3",style: "color: #3e8d92;" %>
    <%= link_to "プライバシーポリシー", privacy_path, class: "footer_link mx-3", style: "color: #3e8d92;"  %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e9c9d5;">
  <div class="navbar-brand">
    <%= link_to root_path do %>
      <%= image_tag 'Logo.png', size: "70x70" %>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if admin_signed_in? %>
        <% if request.fullpath.include?("/admin")%>
          <!--adminログイン後のリンク-->
          <li class="nav-item">
            <%= link_to admin_users_path, class: "nav-link mr-3",style: "color: #3e8d92;" do %>
              <i class="fa-solid fa-users"></i> ユーザー一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_path, class: "nav-link mr-3",style: "color: #3e8d92;" do %>
              <i class="fa-regular fa-rectangle-list"></i> 投稿一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_inquiries_path, class: "nav-link mr-3",style: "color: #3e8d92;" do %>
              <i class="fa-solid fa-inbox"></i> お問い合わせ一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link mr-3",style: "color: #3e8d92;" do %>
              <i class="fa-solid fa-person-walking-arrow-right"></i> ログアウト
            <% end %>
          </li>
        <% end %>
      <% elsif user_signed_in? %>
        <% unless request.fullpath.include?("/admin") %>
          <!--userログイン後のリンク-->

          <li class="nav-item">
            <%= link_to posts_path, class: "nav-link mr-3", style: "color: #3e8d92;" do %>
              <i class="fa-regular fa-rectangle-list"></i> 投稿一覧
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to my_page_path, class: "nav-link mr-3",style: "color: #3e8d92;" do %>
              <i class="fa-solid fa-user"></i> マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link mr-3", style: "color: #3e8d92; position: relative;" do %>
              <% if current_user.notifications.where(checked: false).exists? %>
                <i class="fa-solid fa-bell fa-lg"></i>
                <span class="notification-badge">
                  <%= current_user.notifications.where(checked: false).count %>
                </span>
              <% else %>
                <i class="fa-regular fa-bell"></i>
              <% end %>
              通知
            <% end %>
          </li>
          <li class="nav-item">
            <%=link_to destroy_user_session_path, method: :delete, class: "nav-link mr-3",style: "color: #3e8d92;" do %>
              <i class="fa-solid fa-person-walking-arrow-right"></i> ログアウト
            <% end %>
          </li>
        <% end %>
      <% else %>
        <% unless request.fullpath.include?("/admin")%>
          <!--userログイン前のリンク-->
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link mr-3",style: "color: #3e8d92;" do %>
              <i class="fa-solid fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link mr-3",style: "color: #3e8d92;" do %>
              <i class="fa-solid fa-door-open"></i> ログイン
            <% end %>
          </li>
        <% else %>
          <!--adminログイン前のリンク-->
          <li class="nav-item">
            <%= link_to new_admin_session_path, class: "nav-link mr-5",style: "color: #3e8d92;" do %>
              <i class="fa-solid fa-door-open"></i> ログイン
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_search_btn.html.erb
<div class="form-group d-flex mt-5">
  <div class="col-7">
    <%= f.text_field :word, class: "form-control", placeholder: "キーワード" %>
    <%= f.hidden_field :search, value: 'partial' %>
  </div>
  <div class="col-5">
    <%= f.submit "検索", class: "btn btn_search btn-block" %>
  </div>
</div>
<div class="button_radio pl-2">
  <%= f.radio_button :model,"ユーザー",checked: true %>
  <%= f.label "ユーザー" %>
  <%= f.radio_button :model,"投稿" %>
  <%= f.label "投稿" %>
</div>

app/views/layouts/_search_form.html.erb
<% if admin_signed_in? %>
  <%= form_with url: admin_search_path, method: :get do |f| %>
    <%= render 'layouts/search_btn', f: f %>
  <% end %>
<% elsif user_signed_in? %>
  <%= form_with url: search_path, method: :get do |f| %>
    <%= render 'layouts/search_btn', f: f %>
  <% end %>
<% else %>
<% end %>

app/views/layouts/_sideber.html.erb
<!--投稿一覧＆ユーザー一覧-->
<% unless admin_signed_in? %>
  <div class="col-12 my-4">
    <%= link_to new_post_path, style: "color: #3e8d92;" do %>
      <i class="fa-solid fa-pen-to-square"></i> 新規投稿
    <% end %>
  </div>

  <div class="col-12 mb-3">
    <%= link_to users_path, style: "color: #3e8d92;" do %>
      <i class="fa-solid fa-users"></i> ユーザー一覧
    <% end %>
  </div>
<% end %>
<!--ジャンル関係-->
<div class="row pl-2">
  <div class="col-12 my-3">
    <% if admin_signed_in? %>
      <!--adminログイン後のリンク-->
      <% if request.fullpath.include?("/admin")%>
        <%= link_to admin_genres_path,style: "color: #3e8d92;" do %>
          <i class="fa-solid fa-tags"></i>ジャンル一覧
        <% end %>
      <% end %>
    <% else user_signed_in? %>
      <!--userログイン後のリンク-->
      <% unless request.fullpath.include?("/admin") %>
        <%= link_to genres_path,style: "color: #3e8d92;" do %>
          <i class="fa-solid fa-tags"></i>ジャンル一覧
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="col-11">
    <table class="table border">
      <thead>
        <tr>
          <th>ジャンル</th>
          <th>
            <span class="genre_counter">
              <%= total_genres_count %>
            </span>
          </th>
        </tr>
      </thead>
      <tbody>
        <% genres.each do |genre| %>
          <tr>
            <td>
              <% if admin_signed_in? %>
                <% if request.fullpath.include?("/admin")%>
                  <!--adminログイン後のリンク-->
                  <%= link_to "#{genre.name}", admin_genre_path(genre),style: "color: #3e8d92;"%>
                <% end %>
              <% else user_signed_in? %>
                <% unless request.fullpath.include?("/admin") %>
                  <!--userログイン後のリンク-->
                  <%= link_to "#{genre.name}", genre_path(genre),style: "color: #3e8d92;"%>
                <% end %>
              <% end %>
            </td>
            <td>
              <span class="genre_counter">
                <%= genre.posts.count %>
              </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row justify-content-center">
      <div class="col-10">
        <%= paginate @genres, param_name: :sidebar_page %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oshi Life</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/7be1f5c9f4.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <div id="wrapper">
      <header>
        <%= render 'layouts/header' %>
      </header>
      <div class="text-center">
        <p class="notice mb-0 mt-1"><%= notice %></p>
        <p class="alert m-0"><%= alert %></p>
      </div>
      <div class="container-fluid">
        <div class="row">
          <% if @show_sidebar == false %>
            <div class="col-lg-12">
              <main>
                <%= yield %>
              </main>
            </div>
          <% else %>
          <!-- サイドバー -->
          <div class="col-lg-3 offset-lg-1 d-none d-lg-block my-5" id="sidebar">
            <!-- サイドバーのコンテンツ -->
            <div class="card2">
              <div class="d-flex justify-content-center">
                <%= render 'layouts/search_form' %>
              </div>
              <%= render 'layouts/sideber', genres: @genres, total_genres_count: @total_genres_count%>
            </div>
          </div>

          <!-- スマートフォンサイズの場合、検索機能をメインコンテンツの上に移動 -->
          <div class="col-12 d-lg-none mb-3">
            <div class="d-flex justify-content-center">
              <%= render 'layouts/search_form' %>
            </div>
          </div>
          <!-- メインコンテンツ -->
          <div class="col-lg-8">
            <main>
              <%= yield %>
            </main>
          </div>
        </div>
          <!-- スマートフォンサイズの場合、サイドバーはメインコンテンツの下に移動 -->
          <div class="d-lg-none d-flex justify-content-center mb-5">
            <div class="col-10 card2">
            <%= render 'layouts/sideber', genres: @genres, total_genres_count: @total_genres_count %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>